info:
  component: Weatherbit.io Client and API

spring:
  application:
    name: weatherbit-io-api
  profiles:
    include:
      - weatherbit
      - swagger

server:
  port: ${port:8080}

logging:
  file: ${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level [AppName=${spring.application.name}] [trace=%X{X-B3-TraceId:-}, span=%X{X-B3-SpanId:-}] [LogMessage=%m]%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level [AppName=${spring.application.name}] [trace=%X{X-B3-TraceId:-}, span=%X{X-B3-SpanId:-}] [LogMessage=%m]%n"
  level:
    root: INFO

root:
  config:
    title: Weatherbit.io Client and REST API
    description: Spring Boot REST API and client for Weatherbit.io
    version: 1.0.0
    contactName: Christian Leon
    contactUrl: https://www.linkedin.com/in/christianrleon
    contactEmail: crleon09@gmail.com